from google import genai
from google.genai import types
import os
import json
import re
from datetime import date
from pathlib import Path

# --- Configuration ---
client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

BLOG_DIR = Path("src/data/blog") 
EXCLUDE_POSTS_WITH_TAGS = ["economics"]
PROMPT_PATH = Path(".github/prompts/outdated-check.md")
MODEL = "gemini-3-flash-preview" 
# ---------------------

def get_tags(content: str) -> list[str]:
    """Extract tags from Astro frontmatter."""
    match = re.search(r'^---\s*\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return []
    frontmatter = match.group(1)
    
    # Try block list format
    tags_match = re.search(r'^tags:\s*\n((?:\s+-\s+.+\n?)+)', frontmatter, re.MULTILINE)
    if tags_match:
        return re.findall(r'-\s+(.+)', tags_match.group(1))
    
    # Try inline format
    inline_match = re.search(r'^tags:\s*\[(.+)\]', frontmatter, re.MULTILINE)
    if inline_match:
        return [t.strip().strip('"\'') for t in inline_match.group(1).split(',')]
    
    return []

def is_excluded(content: str) -> bool:
    tags = {t.lower().strip() for t in get_tags(content)}
    excluded = {t.lower().strip() for t in EXCLUDE_POSTS_WITH_TAGS}
    return bool(tags & excluded)

# 1. Collect Posts
if not BLOG_DIR.exists():
    print(f"Error: {BLOG_DIR} not found.")
    exit(1)

posts = []
for filepath in sorted(list(BLOG_DIR.glob("*.md")) + list(BLOG_DIR.glob("*.mdx"))):
    content = filepath.read_text()
    if not is_excluded(content):
        posts.append({"filename": filepath.name, "path": str(filepath), "content": content})

if not posts:
    print("No eligible posts found.")
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write("changes_made=false\ncreate_pr=false\n")
    exit(0)

# 2. Build Prompt
prompt_template = PROMPT_PATH.read_text()
posts_block = "\n\n".join(
    f'<post filename="{p["filename"]}" path="{p["path"]}">{p["content"]}</post>'
    for p in posts
)
full_prompt = prompt_template.replace("{{POSTS}}", posts_block).replace("{{TODAY}}", str(date.today()))

print(f"Sending {len(posts)} posts to Gemini...")

# 3. Generate Content
response = client.models.generate_content(
    model=MODEL,
    contents=full_prompt,
    config=types.GenerateContentConfig(
        response_mime_type="application/json",
        response_schema={
            "type": "OBJECT",
            "properties": {
                "create_pr": {"type": "BOOLEAN"},
                "pr_title": {"type": "STRING"},
                "pr_body": {"type": "STRING"},
                "file_changes": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "properties": {
                            "path": {"type": "STRING"},
                            "content": {"type": "STRING"}
                        }
                    }
                }
            }
        }
    ),
)

result = response.parsed 

if not result:
    import json
    result = json.loads(response.text)

# 4. Apply changes
changes_made = False
for change in result.get("file_changes", []):
    path = Path(change["path"])
    if path.is_relative_to(BLOG_DIR):
        path.write_text(change["content"])
        print(f"Updated: {path}")
        changes_made = True

create_pr = changes_made and result.get("create_pr", False)

# 5. GitHub Outputs
if "GITHUB_OUTPUT" in os.environ:
    with open(os.environ["GITHUB_OUTPUT"], "a") as f:
        f.write(f"changes_made={str(changes_made).lower()}\n")
        f.write(f"create_pr={str(create_pr).lower()}\n")

        title = result.get("pr_title", "Update Outdated Content").replace("\n", " ")
        f.write(f"pr_title={title}\n")

        body = result.get("pr_body", "Auto-generated by outdated-check.py").replace("\\n", "\n")
        f.write("pr_body<<EOF\n")
        f.write(body)
        f.write("\nEOF\n")

print(f"Done. Changes: {changes_made}")
